name: Docker Image CI

on: [push]

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/puthon3:latest
#  push:
#    branches:
#      - 'master'
#jobs:
#  run_tests:
#    runs-on: [ubuntu-latest]
#    steps:
#      # Чекаутим код
#      - uses: actions/checkout@master
#      # Устанавливаем python нужной версии
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.11'
#          architecture: 'x64'
#      - name: Install requirements
#        # Устанавливаем зависимости
#        run: pip install -r requirements.txt
