name: Docker Image CI

on: [push]
#  push:
#    branches:
#      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build python:3.11-alpine3.18
      run: |
        docker build ./
