name: Docker Image CI

on: 
  push:
    branches:
      - 'master'
jobs:
  build-container:
    name: Build Docker container image
    runs-on: python:3.11-alpine3.18
    steps:
      - name: docker build 
        uses: actions/checkout@v2
        run: |
          docker build ./
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python3:latest
